// GRADE 4 STUDENTS 2024
export const Grade1 = [
    {
        StudentFullName: "John Doe",
        AssessmentNumber: "G1-001",
        UPI: "UPI001",
        EntryNo: "E001",
        Gender: "Male",
        classfilteringCode: "1A",
        classfilteringbyGender: "Boys",
        CurentGrade: "Grade 1",
        FileUrl1: "./img/people.png",
    classfilteringCode: "",
    Disability: "",
    DateOfAdm: "🕸️",
    AdmissionClass: "🕸️",
    DateOfBirth: "",
    UPI: "🕸️",
    PhoneNumber: "🕸️",
    StudentSchoolEmail: "🕸️",
    ClassTeacher: "🕸️",
    FathersName: "🕸️",
    FathersPhoneNumber: "🕸️",
    MothersName: "🕸️",
    MothersPhoneNumber: "🕸️",
    Siblings: "No1:Tom allan \n No2: Joy amalia",
    FileUrl1: "./img/logo.png",
    FileUrl2: "",
    FileUrl3: "🕸️",
    FileUrl4: "",
  },
  {
    CurentGrade: "Grade 1",
    StudentFullName: "gEOFREY ODUOR",
     Status:"",
    Year: "2025",
    AdmissionNo: "",
    AssessmentNumber: "",
    EntryNo: "",
    Gender: "Male",
    classfilteringbyGender: "",
    classfilteringCode: "",
    Disability: "",
    DateOfAdm: "28377",
    AdmissionClass: "🕸️",
    DateOfBirth: "",
    UPI: "🕸️",
    PhoneNumber: "🕸️",
    StudentSchoolEmail: "🕸️",
    ClassTeacher: "🕸️",
    FathersName: "🕸️",
    FathersPhoneNumber: "🕸️",
    MothersName: "🕸️",
    MothersPhoneNumber: "🕸️",
    Siblings: "No1:Tom allan \n No2: Joy amalia",
    FileUrl1: "./img/logo.png",
    FileUrl2: "",
    FileUrl3: "./img/people.png",
    FileUrl4: "../img/Students.jpg",
  },
  
    // Add more default data objects as needed
  ];
  
   
  