// GRADE 3 STUDENTS 2024
export const Grade4 = [
    {
      CurentGrade: "Grade 4",
      Status:"Active",
      StudentFullName: "AKATCH SAMUEL ODHIAMBO",
      AssessmentNumber: "B006437471",
      Gender: "#Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##04",
      EntryNo: "431452166",
      AdmissionNo: "001/24",
      Disability: "None",
      DateOfAdm: "XXXXXXXXXXXX",
      AdmissionClass: "XXXXXXXXXXXX",
      DateOfBirth: "25-08-14",
      UPI: "K254",
      PhoneNumber: "XXXXXXXXXXXX",
      StudentSchoolEmail: "XXXXXXXXXXXX",
      ClassTeacher: "🧑‍⚕️ Mr Oduor Geofrey Onyango",
      ParentGuardianName: "XXXXXXXXXXXX",
      ParentGuardianPhoneNumber: "XXXXXXXXXXXX",
      Siblings: "XXXXXXXXXXX",
      FileUrl1: "#",
      FileUrl2: "#",
      FileUrl3: "#",
      FileUrl4: "../img/Students.jpg",
    },
    {
      CurentGrade: "Grade 4",
      Status:"Active",
      AssessmentNumber: "B006442226",
      StudentFullName: "ARINDO MICHAEL OTIENO",
      EntryNo: "432017504",
      Gender: "#Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##04",
      AdmissionNo: "002/24",
      Disability: "None",
      DateOfAdm: "XXXXXXXXXXXX",
      AdmissionClass: "XXXXXXXXXXXX",
      DateOfBirth: "09-09-2017",
      UPI: "P3TTRZ",
      PhoneNumber: "XXXXXXXXXXXX",
      StudentSchoolEmail: "XXXXXXXXXXXX",
      ClassTeacher: "🧑‍⚕️ Mr Oduor Geofrey Onyango",
      ParentGuardianName: "XXXXXXXXXXXX",
      ParentGuardianPhoneNumber: "XXXXXXXXXXXX",
      Siblings: "XXXXXXXXXXX",
      FileUrl1: "#",
      FileUrl2: "#",
      FileUrl3: "#",
      FileUrl4: "../img/Students.jpg",
    
    },
    {
      CurentGrade: "Grade 4",
      Status:"Active",
      AssessmentNumber: "8888",
      StudentFullName: "BUORO SAMANTHA MARION",
      Gender: "#Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##04",
      EntryNo: "",
      AdmissionNo: "003/24",
      Disability: "None",
      DateOfAdm: "XXXXXXXXXXXX",
      AdmissionClass: "XXXXXXXXXXXX",
      DateOfBirth: "",
      UPI: "",
      PhoneNumber: "XXXXXXXXXXXX",
      StudentSchoolEmail: "XXXXXXXXXXXX",
      ClassTeacher: "🧑‍⚕️ Mr Oduor Geofrey Onyango",
      ParentGuardianName: "XXXXXXXXXXXX",
      ParentGuardianPhoneNumber: "XXXXXXXXXXXX",
      Siblings: "XXXXXXXXXXX",
      FileUrl1: "#",
      FileUrl2: "#",
      FileUrl3: "#",
      FileUrl4: "../img/Students.jpg",
    
    },
    {
      CurentGrade: "Grade 4",
      Status:"Active",
      AssessmentNumber: "B006458469",
      StudentFullName: "CHRISTINE AWUOR",
      EntryNo: "",
      Gender: "#Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##04",
      AdmissionNo: "004/24",
      Disability: "None",
      DateOfAdm: "XXXXXXXXXXXX",
      AdmissionClass: "XXXXXXXXXXXX",
      DateOfBirth: "",
      UPI: "",
      PhoneNumber: "XXXXXXXXXXXX",
      StudentSchoolEmail: "XXXXXXXXXXXX",
      ClassTeacher: "🧑‍⚕️ Mr Oduor Geofrey Onyango",
      ParentGuardianName: "XXXXXXXXXXXX",
      ParentGuardianPhoneNumber: "XXXXXXXXXXXX",
      Siblings: "XXXXXXXXXXX",
      FileUrl1: "#",
      FileUrl2: "#",
      FileUrl3: "#",
      FileUrl4: "../img/Students.jpg",
    
    
    },
  
    {
    CurentGrade: "Grade 4",
    Status:"Active",
    AssessmentNumber: "B006479291",
    StudentFullName: "DANIEL OTIENO OKUMU",
    EntryNo: "",
    Gender: "#Male",
    classfilteringbyGender: "#M09",
    classfilteringCode: "##04",
    AdmissionNo: "005/24",
    Disability: "None",
    DateOfAdm: "XXXXXXXXXXXX",
    AdmissionClass: "XXXXXXXXXXXX",
    DateOfBirth: "",
    UPI: "",
    PhoneNumber: "XXXXXXXXXXXX",
    StudentSchoolEmail: "XXXXXXXXXXXX",
    ClassTeacher: "🧑‍⚕️ Mr Oduor Geofrey Onyango",
    ParentGuardianName: "XXXXXXXXXXXX",
    ParentGuardianPhoneNumber: "XXXXXXXXXXXX",
    Siblings: "XXXXXXXXXXX",
    FileUrl1: "#",
    FileUrl2: "#",
    FileUrl3: "#",
    FileUrl4: "../img/Students.jpg"},
    // Add more default data objects as needed
  ];
  
   
  