// GRADE 4 STUDENTS 2024
export const Grade6 = [

  
  {
    AssessmentNumber:"A001749771", 
  StudentFullName:	"OMONDI PAREL OCHIENG	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431346639"	,      
  DateOfBirth:"01/12/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002105962", 
  StudentFullName:	"OGOT CAROLINE ATIENO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431984087"	,      
  DateOfBirth:"10/05/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002198332", 
  StudentFullName:	"OTIENO HELLEN ATIENO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431983390"	,      
  DateOfBirth:"12/04/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002198634", 
  StudentFullName:	"OKOTH VENIA ANYANGO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 602100576"	,      
  DateOfBirth:"12/06/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002198816", 
  StudentFullName:	"OKUMU EMMANUEL ONYANGO	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 0"	,              
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002198922", 
  StudentFullName:	"ONYANGO EUNICE AKOTH	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 432139812"	,      
  DateOfBirth:"18/09/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002199129", 
  StudentFullName:	"ODONGO,BENARD OKECH	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431418222"	,      
  DateOfBirth:"04/12/2014",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002199293", 
  StudentFullName:	"OTIENO SANDRA JOYLET AKINYI",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431972039"	,      
  DateOfBirth:"26/01/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002362886", 
  StudentFullName:	"OMONDI VICTOR OTIENO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002363011", 
  StudentFullName:	"MAYAMBA PHENNY APIYO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431452176"	,      
  DateOfBirth:"30/07/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002363164", 
  StudentFullName:	"OLUOCH MELVINE AKINYI	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 3539LNYP"	,       
   DateOfBirth:"16/07/2011", 
    CurentGrade: "Grade 6",  
     AdmissionNo: " ",  
      Status:"",  
       Siblings: "No1:Tom allan \n No2: Joy amalia",  
        FileUrl1: "",  
         FileUrl2: "", 
          FileUrl3: "🕸️",  
           FileUrl4: "./img/Students.jpg",  }
      
             ,
  {
    AssessmentNumber:"A002363358", 
  StudentFullName:	"OMONDI MARION AKINYI	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431974156"	,      
  DateOfBirth:"10/05/2009",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002363382", 
  StudentFullName:	"OMONDI YVONNE AUMA	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431833683"	,      
  DateOfBirth:"02/10/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002363450", 
  StudentFullName:	"OTIENO JENIPHER APIYO	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 3521LNYP"	,       
   DateOfBirth:"12/04/2012", 
    CurentGrade: "Grade 6",  
     AdmissionNo: " ",  
      Status:"",  
       Siblings: "No1:Tom allan \n No2: Joy amalia",  
        FileUrl1: "",  
         FileUrl2: "", 
          FileUrl3: "🕸️",  
           FileUrl4: "./img/Students.jpg",  }
      
             ,
  {
    AssessmentNumber:"A002363480", 
  StudentFullName:	"OTIENO MERYL ADHIAMBO	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 3509LNYP"	,       
   DateOfBirth:"02/02/2013", 
    CurentGrade: "Grade 6",  
     AdmissionNo: " ",  
      Status:"",  
       Siblings: "No1:Tom allan \n No2: Joy amalia",  
        FileUrl1: "",  
         FileUrl2: "", 
          FileUrl3: "🕸️",  
           FileUrl4: "./img/Students.jpg",  }
      
             ,
  {
    AssessmentNumber:"A002363549", 
  StudentFullName:	"OUMA DICKENS OTIENO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 41416242"	,       
   DateOfBirth:"22/06/2011", 
    CurentGrade: "Grade 6",  
     AdmissionNo: " ",  
      Status:"",  
       Siblings: "No1:Tom allan \n No2: Joy amalia",  
        FileUrl1: "",  
         FileUrl2: "", 
          FileUrl3: "🕸️",  
           FileUrl4: "./img/Students.jpg",  }
      
             ,
  {
    AssessmentNumber:"A002363573", 
  StudentFullName:	"OUMA HELLEN VALARY ATIENO  ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002363588", 
  StudentFullName:	"OUMA MIKE OTIENO	          ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 601411480"	,      
  DateOfBirth:"06/11/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002363639", 
  StudentFullName:	"OWINO SHEILA ADHIAMBO      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431625361"	,      
  DateOfBirth:"05/01/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002494640", 
  StudentFullName:	"OCHIENG STEPHEN OTIENO	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"05/10/2010",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002494651", 
  StudentFullName:	"OCHIENG MARK OMONDI	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"06/05/2008",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"A002494659", 
  StudentFullName:	"LANGU TYRON OTIENO	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 432404665"	,      
  DateOfBirth:"29/12/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001514116", 
  StudentFullName:	"IMBO SAMUEL OTIENO	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431849429"	,      
  DateOfBirth:"26/08/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001514333", 
  StudentFullName:	"MAYAMBA WINNIE ADONGO      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431452113"	,      
  DateOfBirth:"30/07/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001514473", 
  StudentFullName:	"OMBOK CATHRINE ADHIAMBO    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	432017505"	,      
  DateOfBirth:"30/05/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001515476", 
  StudentFullName:	"OTIENO JAMES NICKSON ODUOR ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431417906"	,      
  DateOfBirth:"30/07/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001517383", 
  StudentFullName:	"OUMA WILLIAM ODHIAMBO	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 0"	,              
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001517988", 
  StudentFullName:	"OCHIENG AUSTINE ODIWUOR	  ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 0"	,              
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001519059", 
  StudentFullName:	"ONYANGO BARACK OMONDI	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431536307"	,      
  DateOfBirth:"27/11/2008",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001719850", 
  StudentFullName:	"OTIENO JOSEPH WASONGA      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001719871", 
  StudentFullName:	"ODHIAMBO DENIS OTIENO      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001719888", 
  StudentFullName:	"OWINO VENESSA AUMA	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001719932", 
  StudentFullName:	"AKATCH TITUS OTIENO	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720036", 
  StudentFullName:	"OBAJE CALEB OCHUKA	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720073", 
  StudentFullName:	"ODHIAMBO EDITH ACHIENG	    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431984057"	,      
  DateOfBirth:"07/03/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720099", 
  StudentFullName:	"ODHIAMBO GEORGE OCHIENG    ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431984196"	,      
  DateOfBirth:"24/07/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720129", 
  StudentFullName:	"ODHIAMBO ROSE AWUOR	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431701906"	,      
  DateOfBirth:"11/08/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720333", 
  StudentFullName:	"OMBOK HOLYFILLED OCHIENG   ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431701882"	,      
  DateOfBirth:"23/10/2010",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720386", 
  StudentFullName:	"OMBOK ROMANUS RAILA	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431701890"	,      
  DateOfBirth:"13/02/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720596", 
  StudentFullName:	"ANINDO GLEN OPONDO	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 3505LNYP"	,       
   DateOfBirth:"23/12/2012", 
    CurentGrade: "Grade 6",  
     AdmissionNo: " ",  
      Status:"",  
       Siblings: "No1:Tom allan \n No2: Joy amalia",  
        FileUrl1: "",  
         FileUrl2: "", 
          FileUrl3: "🕸️",  
           FileUrl4: "./img/Students.jpg",  }
      
             ,
  {
    AssessmentNumber:"B001720707", 
  StudentFullName:	"OTIENO PAUL OMONDI         ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	5656LNYP"	,       
   DateOfBirth:"16/04/2009", 
    CurentGrade: "Grade 6",  
     AdmissionNo: " ",  
      Status:"",  
       Siblings: "No1:Tom allan \n No2: Joy amalia",  
        FileUrl1: "",  
         FileUrl2: "", 
          FileUrl3: "🕸️",  
           FileUrl4: "./img/Students.jpg",  }
      
             ,
  {
    AssessmentNumber:"B001720747", 
  StudentFullName:	"OUMA CHARLES ODHIAMBO      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	431374912"	,      
  DateOfBirth:"10/09/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720788", 
  StudentFullName:	"OUMA EVALINE AWINO	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 211136557"	,      
  DateOfBirth:"06/08/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001720872", 
  StudentFullName:	"OWINO JULIA ACHIENG	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" XXXXX"	,          
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B001983278", 
  StudentFullName:	"OCHIENG MARYANNE AKOTH     ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	502408529"	,      
  DateOfBirth:"10/07/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B002304691", 
  StudentFullName:	"BUORO EUGINE ESMA	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431940724"	,      
  DateOfBirth:"26/03/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B002306377", 
  StudentFullName:	"ONDIASO,FRANK LENOX	      ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 431612506"	,      
  DateOfBirth:"18/09/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B003351882", 
  StudentFullName:	"WINDA ESTHER JUMA	        ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 0"	,              
  DateOfBirth:"01/01/2013",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B003439011", 
  StudentFullName:	"OWINO TRIZAH ANGEL ACHIENG ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:"	432402850"	,      
  DateOfBirth:"16/10/2012",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },

  {
    AssessmentNumber:"B003441588", 
  StudentFullName:	"OUMA JOHN OWINO	          ",    
  UPI: "",
  PhoneNumber: "🕸️",     
  StudentSchoolEmail: "🕸️",     
  ClassTeacher: "🕸️",   
  FathersName: "🕸️", 
  FathersPhoneNumber: "🕸️", 
  MothersName: "🕸️",   
  MothersPhoneNumber: "🕸️",  
  YearOfGraduation:"2024",  
  Gender: "I",    
  classfilteringbyGender: "",     
  classfilteringCode: "",   
  Disability: "",    
  DateOfAdm: "🕸️",   
  AdmissionClass: "🕸️",   
  EntryNo:" 0"	,              
  DateOfBirth:"01/01/2011",  
  CurentGrade: "Grade 6",   
  AdmissionNo: " ",   
  Status:"",   
  Siblings: "No1:Tom allan \n No2: Joy amalia",   
  FileUrl1: "",   
  FileUrl2: "",  
  FileUrl3: "🕸️",   
  FileUrl4: "./img/Students.jpg",  
  },


  

   
    // Add more default data objects as needed
  ];
  
   
  