// GRADE 4 STUDENTS 2024
export const Grade9 = [
  {
     CurentGrade: "Grade 9",
     StudentFullName: "EVELYN ACHIENG",
     Status:"Active",
      AdmissionNo: "012/25",
      AssessmentNumber: "A000289134",
      EntryNo: "0431452153",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "2012",
      AdmissionClass: "Grade 3",
      DateOfBirth: "25-08-14",
      UPI: "G167KK",
      PhoneNumber: "N/A",
      StudentSchoolEmail: "N/A",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "TOM ONYANGO OLOO",
      FathersPhoneNumber: "07XXXXXXXXXXX",
      MothersName: "ALICE ATIENO ",
      MothersPhoneNumber: "07XXXXXX-XXXXXX",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "../Pdf/2023-KCPE-Timetable-04.05.pdf",
      FileUrl2: "../Pdf/2023-KCPE-Timetable-04.05.pdf",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Grade 9 2025/Evelyn.jpg",
    },

  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "011/25",
      YearOfGraduation:"2025",
      AssessmentNumber: "A000261919",
      StudentFullName: "OWAGA HARUN OMONDI",
      EntryNo: "0431932571",
      Gender: "Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##09",
      Disability: "None",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "010/25",
      AssessmentNumber: "A000220157",
      StudentFullName: "ODHIAMBO PATRICIA AMONDI",
      EntryNo: "0431983626",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "#09/25",
      AssessmentNumber: "A000184885",
      StudentFullName: "AKATCH MILLICENT AKINYI",
      EntryNo: "0431983624",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "008/25",
      AssessmentNumber: "A000173074",
      StudentFullName: "ODUOR SYNTHIA ACHIENG",
      EntryNo: "0431863727",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "007/25",
      AssessmentNumber: "A000171552",
      StudentFullName: "ONYANGO BRENDA ADHIAMBO",
      EntryNo: "0432017564",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
    
  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "006/25",
      AssessmentNumber: "A000164111",
      StudentFullName: "OOKO MILTON OCHIENG",
      EntryNo: "0431606675",
      Gender: "Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    

  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AdmissionNo: "005/25",
      AssessmentNumber: "A000161996",
      StudentFullName: "OWUOR COLLINS OCHIENG",
      Gender: "Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##09",
      EntryNo: "0431003230",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AssessmentNumber: "A000127458",
      StudentFullName: "ODENYO WASHINGTONE OTIENO",
      Gender: "Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##09",
      EntryNo: "0431622492",
      AdmissionNo: "004/25",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },

  {
      CurentGrade: "Grade 9",
       Status:"Active",
      AssessmentNumber: "A000107684",
      StudentFullName: "MOWLEN ANN AMONDI",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      classfilteringCode: "##09",
      EntryNo: "430801714",
      AdmissionNo: "003/25",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },

  {
      CurentGrade: "Grade 9",
       Status:"Active",
      StudentFullName: "RAWER ROBERT KELLY OTIENO",
      AssessmentNumber: "A000043571",
      Gender: "Male",
      classfilteringbyGender: "#M09",
      classfilteringCode: "##09",
      EntryNo: "0431452158",
      AdmissionNo: "002/25",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
    
    {
      CurentGrade: "Grade 9",
       Status:"Active",
      AssessmentNumber: "A000011219",
      Gender: "Female",
      classfilteringbyGender: "#F09",
      StudentFullName: "OKOTH VIVIAN ACHIENG",
      AdmissionNo: "001/24",
      EntryNo: "0431938390",
      classfilteringCode: "##09",
      Disability: "None",
       YearOfGraduation:"2025",
      DateOfAdm: "🕸️",
      AdmissionClass: "🕸️",
      DateOfBirth: "25-08-14",
      UPI: "🕸️",
      PhoneNumber: "🕸️",
      StudentSchoolEmail: "🕸️",
      ClassTeacher: "Mr Wyclife Owino ",
      FathersName: "🕸️",
      FathersPhoneNumber: "🕸️",
      MothersName: "🕸️",
      MothersPhoneNumber: "🕸️",
      Siblings: "No1:Tom allan \n No2: Joy amalia",
      FileUrl1: "🕸️",
      FileUrl2: "🕸️",
      FileUrl3: "🕸️",
      FileUrl4: "./img/Students.jpg",
    },
   
    // Add more default data objects as needed
  ];
  
   
  